name: dartrosa_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/dartrosa
  - packages/dartrosa_encryption
  - packages/dartrosa_entities
  - packages/dartrosa_external_data
  - packages/dartrosa_openrosa
  - packages/dartrosa_collect
  - packages/dartrosa_calendars

dev_dependencies:
  lints: ^6.1.0
