// Copyright 2026 The DartRosa Authors
// SPDX-License-Identifier: Apache-2.0

import bikramsambat.BikramSambatDate;
import bikramsambat.BsCalendar;
import bikramsambat.BsException;
import bikramsambat.BsGregorianDate;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import mmcalendar.Language;
import mmcalendar.MyanmarCalendarKernel;
import mmcalendar.MyanmarDate;
import org.joda.time.Chronology;
import org.joda.time.DateTime;
import org.joda.time.LocalDateTime;
import org.joda.time.chrono.BuddhistChronology;
import org.joda.time.chrono.CopticChronology;
import org.joda.time.chrono.EthiopicChronology;
import org.joda.time.chrono.GregorianChronology;
import org.joda.time.chrono.IslamicChronology;
import org.joda.time.chrono.PersianChronologyKhayyamBorkowski;
import org.odk.collect.android.utilities.MyanmarDateUtils;

/**
 * Generates test vectors for dartrosa_calendars by running the calendar
 * libraries ODK Collect uses, the way Collect's date pickers and
 * DateTimeWidgetUtils call them.
 *
 * <p>Day numbers are days since 1970-01-01 (proleptic Gregorian). Every
 * table is "transition" encoded: a row is written only where the value is
 * not the previous row's value advanced by one day.
 */
public final class CalendarOracle {
    static final int FROM = (int) LocalDate.of(1880, 1, 1).toEpochDay();
    static final int TO = (int) LocalDate.of(2120, 12, 31).toEpochDay();

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args[0]);
        Files.createDirectories(out);
        joda(out, "ethiopian", EthiopicChronology.getInstance(), 1893, 2093, 13);
        joda(out, "coptic", CopticChronology.getInstance(), 1617, 1817, 13);
        joda(out, "islamic", IslamicChronology.getInstance(), 1318, 1524, 12);
        joda(out, "persian", PersianChronologyKhayyamBorkowski.getInstance(), 1278, 1478, 12);
        joda(out, "buddhist", BuddhistChronology.getInstance(), 2443, 2643, 12);
        bikramSambat(out);
        myanmar(out);
    }

    static PrintWriter open(Path out, String name) throws IOException {
        PrintWriter w = new PrintWriter(Files.newBufferedWriter(out.resolve(name + "_vectors.dart"), StandardCharsets.UTF_8));
        w.println("// GENERATED by tool/oracle/oracle.sh from the JVM libraries ODK Collect");
        w.println("// uses. Do not edit.");
        w.println();
        return w;
    }

    static int epochOf(LocalDateTime gregorian) {
        return (int) LocalDate.of(gregorian.getYear(), gregorian.getMonthOfYear(), gregorian.getDayOfMonth()).toEpochDay();
    }

    static LocalDateTime gregorianMidnight(int epochDay) {
        LocalDate d = LocalDate.ofEpochDay(epochDay);
        return new LocalDateTime(d.getYear(), d.getMonthValue(), d.getDayOfMonth(), 0, 0, 0, 0);
    }

    static String row(int... values) {
        StringBuilder b = new StringBuilder("[");
        for (int i = 0; i < values.length; i++) {
            if (i > 0) b.append(", ");
            b.append(values[i]);
        }
        return b.append("],").toString();
    }

    static String dartString(String s) {
        return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'";
    }

    // ---------------------------------------------------------------- Joda

    static void joda(Path out, String name, Chronology chrono, int minYear, int maxYear, int months) throws IOException {
        try (PrintWriter w = open(out, name)) {
            // Gregorian -> calendar, as DateTimeWidgetUtils.getDateTimeLabel and
            // the pickers' setUpDatePicker do it.
            w.println("/// Gregorian day -> [day, year, month, dayOfMonth] transitions.");
            w.println("const " + name + "Forward = <List<int>>[");
            int[] prev = null;
            for (int e = FROM; e <= TO; e++) {
                LocalDateTime c = gregorianMidnight(e).toDateTime().withChronology(chrono).toLocalDateTime();
                int[] cur = {c.getYear(), c.getMonthOfYear(), c.getDayOfMonth()};
                if (prev == null || !(cur[0] == prev[0] && cur[1] == prev[1] && cur[2] == prev[2] + 1)) {
                    w.println("  " + row(e, cur[0], cur[1], cur[2]));
                }
                prev = cur;
            }
            w.println("];");
            w.println();
            // Picker values -> Gregorian, as getCurrentXDate + getDateAsGregorian.
            w.println("/// Picker [year, month, minDay, maxDay, gregorianDayOfMinDay].");
            w.println("const " + name + "Picker = <List<int>>[");
            List<String> irregular = new ArrayList<>();
            for (int y = minYear; y <= maxYear; y++) {
                for (int m = 1; m <= months; m++) {
                    LocalDateTime first = new LocalDateTime(y, m, 1, 0, 0, 0, 0, chrono);
                    int max = first.dayOfMonth().getMaximumValue();
                    int min = first.dayOfMonth().getMinimumValue();
                    int start = epochOf(toGregorian(new LocalDateTime(y, m, min, 0, 0, 0, 0, chrono)));
                    for (int d = min; d <= max; d++) {
                        int g = epochOf(toGregorian(new LocalDateTime(y, m, d, 0, 0, 0, 0, chrono)));
                        if (g != start + d - min) irregular.add(row(y, m, d, g));
                    }
                    w.println("  " + row(y, m, min, max, start));
                }
            }
            w.println("];");
            w.println();
            w.println("/// Picker [year, month, day, gregorianDay] not following the above.");
            w.println("const " + name + "PickerIrregular = <List<int>>[");
            for (String r : irregular) w.println("  " + r);
            w.println("];");
        }
    }

    static LocalDateTime toGregorian(LocalDateTime date) {
        // DateTimeUtils.getDateAsGregorian
        return date.toDateTime().withChronology(GregorianChronology.getInstance()).toLocalDateTime();
    }

    // -------------------------------------------------------- Bikram Sambat

    static void bikramSambat(Path out) throws IOException {
        BsCalendar bs = BsCalendar.getInstance();
        try (PrintWriter w = open(out, "bikram_sambat")) {
            w.println("/// Month names (BsCalendar.MONTH_NAMES).");
            w.println("const bikramSambatMonthNames = <String>[");
            for (String s : BsCalendar.MONTH_NAMES) w.println("  " + dartString(s) + ",");
            w.println("];");
            w.println();
            w.println("/// Gregorian day -> [day, year, month, dayOfMonth] transitions;");
            w.println("/// year -1 where toBik throws.");
            w.println("const bikramSambatForward = <List<int>>[");
            int[] prev = null;
            for (int e = FROM; e <= TO; e++) {
                LocalDate g = LocalDate.ofEpochDay(e);
                int[] cur;
                try {
                    BikramSambatDate b = bs.toBik(new BsGregorianDate(g.getYear(), g.getMonthValue(), g.getDayOfMonth()));
                    cur = new int[] {b.year, b.month, b.day};
                } catch (BsException ex) {
                    cur = new int[] {-1, 0, 0};
                }
                boolean consecutive = prev != null && cur[0] == prev[0] && cur[1] == prev[1]
                        && (cur[0] == -1 || cur[2] == prev[2] + 1);
                if (!consecutive) w.println("  " + row(e, cur[0], cur[1], cur[2]));
                prev = cur;
            }
            w.println("];");
            w.println();
            w.println("/// [year, month, daysInMonth (-1: throws), gregorianDayOf1 (0 if none)]");
            w.println("/// for the picker years 1960..2100.");
            w.println("const bikramSambatPicker = <List<int>>[");
            List<String> irregular = new ArrayList<>();
            for (int y = 1960; y <= 2100; y++) {
                for (int m = 1; m <= 12; m++) {
                    int days;
                    try {
                        days = bs.daysInMonth(y, m);
                    } catch (BsException ex) {
                        days = -1;
                    }
                    int start = 0;
                    if (days > 0) {
                        try {
                            start = epochOf(bs.toGreg(new BikramSambatDate(y, m, 1)));
                            for (int d = 1; d <= days; d++) {
                                int g = epochOf(bs.toGreg(new BikramSambatDate(y, m, d)));
                                if (g != start + d - 1) irregular.add(row(y, m, d, g));
                            }
                        } catch (BsException ex) {
                            start = 0;
                        }
                    }
                    w.println("  " + row(y, m, days, start));
                }
            }
            w.println("];");
            w.println();
            w.println("const bikramSambatPickerIrregular = <List<int>>[");
            for (String r : irregular) w.println("  " + r);
            w.println("];");
        }
    }

    static int epochOf(BsGregorianDate g) {
        return (int) LocalDate.of(g.year, g.month, g.day).toEpochDay();
    }

    // -------------------------------------------------------------- Myanmar

    static void myanmar(Path out) throws IOException {
        Map<String, Integer> names = new LinkedHashMap<>();
        try (PrintWriter w = open(out, "myanmar")) {
            StringBuilder years = new StringBuilder();
            StringBuilder picker = new StringBuilder();
            List<String> irregular = new ArrayList<>();
            for (int y = 1230; y <= 1500; y++) {
                String[] arr = MyanmarDateUtils.getMyanmarMonthsArray(y);
                List<Integer> idx = MyanmarCalendarKernel.calculateRelatedMyanmarMonths(y, 1).getMonthList();
                years.append("  [").append(y);
                for (int i = 0; i < arr.length; i++) {
                    years.append(", ").append(idx.get(i)).append(", ").append(nameId(names, arr[i]));
                }
                years.append("],\n");
                for (int i = 0; i < idx.size(); i++) {
                    int monthIndex = idx.get(i);
                    int len = MyanmarDateUtils.getMonthLength(y, monthIndex);
                    MyanmarDate firstDate = MyanmarDateUtils.createMyanmarDate(y, monthIndex, 1);
                    int first = isFirstYearMonth(y, monthIndex) ? newYearsDay(y) : 1;
                    int start = epochOf(MyanmarDateUtils.myanmarDateToGregorianDate(MyanmarDateUtils.createMyanmarDate(y, monthIndex, 1)));
                    for (int d = 1; d <= Math.max(len, 30); d++) {
                        int g = epochOf(MyanmarDateUtils.myanmarDateToGregorianDate(MyanmarDateUtils.createMyanmarDate(y, monthIndex, d)));
                        if (g != start + d - 1) irregular.add(row(y, monthIndex, d, g));
                    }
                    picker.append("  ").append(row(y, i, monthIndex, first, len, start)).append("\n");
                }
            }
            w.println("/// Myanmar years: [year, monthIndex0, nameId0, monthIndex1, nameId1, ...]");
            w.println("/// as MyanmarCalendarKernel.calculateRelatedMyanmarMonths(year, 1)");
            w.println("/// (Collect's month picker).");
            w.println("const myanmarYears = <List<int>>[");
            w.print(years);
            w.println("];");
            w.println();
            w.println("/// Picker [year, monthId, monthIndex, firstMonthDay, monthLength,");
            w.println("/// gregorianDayOfDay1] (MyanmarDateUtils).");
            w.println("const myanmarPicker = <List<int>>[");
            w.print(picker);
            w.println("];");
            w.println();
            w.println("/// [year, monthIndex, day, gregorianDay] where createMyanmarDate +");
            w.println("/// myanmarDateToGregorianDate is not day-1 + gregorianDayOfDay1.");
            w.println("const myanmarPickerIrregular = <List<int>>[");
            for (String r : irregular) w.println("  " + r);
            w.println("];");
            w.println();
            // Gregorian -> Myanmar as gregorianDateToMyanmarDate / getDateTimeLabel.
            w.println("/// Gregorian day -> [day, year, monthIndex, monthName id (MyanmarDate.getMonthName),");
            w.println("/// monthId (MyanmarDateUtils.getMonthId), dayOfMonth, firstMonthDay, monthLength]");
            w.println("/// transitions.");
            w.println("const myanmarForward = <List<int>>[");
            int[] prev = null;
            for (int e = FROM; e <= TO; e++) {
                LocalDateTime g = gregorianMidnight(e);
                MyanmarDate md = MyanmarDateUtils.gregorianDateToMyanmarDate(g);
                int[] cur = {md.getYearValue(), md.getMonth(), nameId(names, md.getMonthName(Language.MYANMAR)),
                        MyanmarDateUtils.getMonthId(md), md.getDayOfMonth(),
                        MyanmarDateUtils.getFirstMonthDay(md), MyanmarDateUtils.getMonthLength(md)};
                boolean consecutive = prev != null;
                if (consecutive) {
                    for (int i = 0; i < cur.length; i++) {
                        if (cur[i] != (i == 4 ? prev[i] + 1 : prev[i])) consecutive = false;
                    }
                }
                if (!consecutive) {
                    int[] r = new int[cur.length + 1];
                    r[0] = e;
                    System.arraycopy(cur, 0, r, 1, cur.length);
                    w.println("  " + row(r));
                }
                prev = cur;
            }
            w.println("];");
            w.println();
            w.println("/// Month names by id.");
            w.println("const myanmarNames = <String>[");
            for (String s : names.keySet()) w.println("  " + dartString(s) + ",");
            w.println("];");
        }
    }

    static int nameId(Map<String, Integer> names, String name) {
        return names.computeIfAbsent(name, k -> names.size());
    }

    static boolean isFirstYearMonth(int y, int monthIndex) {
        return monthIndex == MyanmarCalendarKernel.calculateRelatedMyanmarMonths(y, 1).getMonthList().get(0);
    }

    static int newYearsDay(int y) {
        return mmcalendar.MyanmarDateKernel.julianToMyanmarDate(mmcalendar.Thingyan.of(y).getMyanmarNewYearDay()).getDayOfMonth();
    }
}
