// Checks the ports of the calendar libraries against vectors generated by
// running the original JVM libraries (tool/oracle/oracle.sh) for every day
// from 1880 to 2120.
import 'package:dartrosa_calendars/src/bikram_sambat.dart';
import 'package:dartrosa_calendars/src/gregorian.dart';
import 'package:dartrosa_calendars/src/joda/basic_chronology.dart';
import 'package:dartrosa_calendars/src/joda/islamic_chronology.dart';
import 'package:dartrosa_calendars/src/joda/persian_chronology.dart';
import 'package:dartrosa_calendars/src/myanmar/myanmar_date_utils.dart';
import 'package:test/test.dart';

import 'vectors/bikram_sambat_vectors.dart';
import 'vectors/coptic_vectors.dart';
import 'vectors/ethiopian_vectors.dart';
import 'vectors/islamic_vectors.dart';
import 'vectors/myanmar_vectors.dart';
import 'vectors/persian_vectors.dart';

final first = epochDayOf(1880, 1, 1);
final last = epochDayOf(2120, 12, 31);

/// Expands transition-encoded rows `[day, v0, v1, ..., vk]` into the value
/// for every day; [advance] gives the value of the day after.
Map<int, List<int>> expand(
  List<List<int>> rows,
  List<int> Function(List<int>) advance,
) {
  final result = <int, List<int>>{};
  var row = 0;
  List<int>? value;
  for (var day = first; day <= last; day++) {
    if (row < rows.length && rows[row][0] == day) {
      value = rows[row].sublist(1);
      row++;
    } else {
      value = advance(value!);
    }
    result[day] = value;
  }
  return result;
}

List<int> nextDay(List<int> v) => [v[0], v[1], v[2] + 1];

void main() {
  test('gregorian helpers round-trip', () {
    for (var day = first; day <= last; day++) {
      final c = civilOf(day);
      expect(epochDayOf(c.year, c.month, c.day), day);
    }
    expect(civilOf(0), (year: 1970, month: 1, day: 1));
  });

  final jodaCases =
      <String, (BasicChronology, List<List<int>>, List<List<int>>)>{
        'Ethiopic': (
          const EthiopicChronology(),
          ethiopianForward,
          ethiopianPicker,
        ),
        'Coptic': (const CopticChronology(), copticForward, copticPicker),
        'Islamic': (const IslamicChronology(), islamicForward, islamicPicker),
        'Persian': (
          const PersianChronologyKhayyamBorkowski(),
          persianForward,
          persianPicker,
        ),
      };
  jodaCases.forEach((name, c) {
    final (chrono, forward, picker) = c;
    test('$name: Gregorian to calendar matches Joda for every day', () {
      final expected = expand(forward, nextDay);
      for (var day = first; day <= last; day++) {
        final f = chrono.fieldsOf(day);
        expect([f.year, f.month, f.day], expected[day], reason: 'day $day');
      }
    });
    test('$name: picker month lengths and calendar to Gregorian', () {
      for (final [year, month, min, max, start] in picker) {
        expect(chrono.maximumDayOfMonth(year, month), max);
        expect(min, 1);
        for (var d = min; d <= max; d++) {
          expect(chrono.epochDayOf(year, month, d), start + d - min);
        }
      }
    });
  });

  group('Bikram Sambat', () {
    const bs = BsCalendar();
    test('toBik matches the jar for every day', () {
      final expected = expand(
        bikramSambatForward,
        (v) => v[0] == -1 ? v : nextDay(v),
      );
      for (var day = first; day <= last; day++) {
        final c = civilOf(day);
        List<int> actual;
        try {
          final b = bs.toBik(c.year, c.month, c.day);
          actual = [b.year, b.month, b.day];
        } on BsException {
          actual = [-1, 0, 0];
        }
        expect(actual, expected[day], reason: '$c');
      }
    });
    test('daysInMonth and toGreg match the jar', () {
      for (final [year, month, days, start] in bikramSambatPicker) {
        if (days == -1) {
          expect(
            () => bs.daysInMonth(year, month),
            throwsA(isA<BsException>()),
          );
          continue;
        }
        expect(bs.daysInMonth(year, month), days);
        for (var d = 1; d <= days; d++) {
          expect(
            bs.toGregorianEpochDay((year: year, month: month, day: d)),
            start + d - 1,
          );
        }
        expect(
          () =>
              bs.toGregorianEpochDay((year: year, month: month, day: days + 1)),
          throwsA(isA<BsException>()),
        );
      }
      expect(BsCalendar.monthNames, bikramSambatMonthNames);
    });
  });

  group('Myanmar', () {
    test('month lists match the library', () {
      for (final row in myanmarYears) {
        final year = row[0];
        final indexes = [for (var i = 1; i < row.length; i += 2) row[i]];
        final names = [
          for (var i = 2; i < row.length; i += 2) myanmarNames[row[i]],
        ];
        expect(
          MyanmarDateUtils.getMonthIndexes(year),
          indexes,
          reason: '$year',
        );
        expect(MyanmarDateUtils.getMyanmarMonthsArray(year), names);
      }
    });
    test('picker values match MyanmarDateUtils', () {
      for (final [year, _, index, firstDay, length, start] in myanmarPicker) {
        expect(MyanmarDateUtils.getFirstMonthDayOf(year, index), firstDay);
        expect(MyanmarDateUtils.getMonthLengthOf(year, index), length);
        for (var d = 1; d <= 30; d++) {
          final date = MyanmarDateUtils.createMyanmarDate(year, index, d);
          expect(
            MyanmarDateUtils.myanmarDateToGregorianDate(date),
            start + d - 1,
            reason: '$year/$index/$d',
          );
        }
      }
    });
    test('Gregorian to Myanmar matches the library for every day', () {
      final expected = expand(
        myanmarForward,
        (v) => [v[0], v[1], v[2], v[3], v[4] + 1, v[5], v[6]],
      );
      for (var day = first; day <= last; day++) {
        final md = MyanmarDateUtils.gregorianDateToMyanmarDate(day);
        expect(
          [
            md.year,
            md.month,
            myanmarNames.indexOf(md.monthName),
            MyanmarDateUtils.getMonthId(md),
            md.dayOfMonth,
            MyanmarDateUtils.getFirstMonthDay(md),
            MyanmarDateUtils.getMonthLength(md),
          ],
          expected[day],
          reason: 'day $day',
        );
      }
    });
  });
}
