#!/usr/bin/env python3
# Copyright 2026 The DartRosa Authors
# SPDX-License-Identifier: Apache-2.0

"""Regenerates test/src/golden_fixtures.dart.

Runs Golden.java (ODK Collect's EncryptionUtils logic on the JVM with
BouncyCastle and kXML 2.3.0, randomness made deterministic) over the inputs in
this directory and embeds inputs, outputs, the RSA test key and Collect's
encrypted test forms as Dart constants (tests also run on the web, where files
can't be read).

Usage: python3 tool/golden/generate.py   (from packages/dartrosa_encryption;
needs java, javac, openssl, and bcprov + kxml2 jars in ~/.gradle/caches).
"""
import base64, glob, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(os.path.dirname(HERE))
GRADLE = os.path.expanduser('~/.gradle/caches/modules-2/files-2.1')


def jar(pattern):
    found = sorted(glob.glob(os.path.join(GRADLE, pattern)))
    if not found:
        sys.exit('missing jar: ' + pattern)
    return found[-1]


CP = ':'.join([jar('org.bouncycastle/bcprov-jdk18on/*/*/bcprov-jdk18on-*.jar'),
               jar('net.sf.kxml/kxml2/2.3.0/*/kxml2-2.3.0.jar')])

CASES = [
    dict(name='withMedia', seed=0, formId='enc-test', version='2024010101',
         instanceId='uuid:2f9b7c0e-1d3a-4e5f-8a6b-9c0d1e2f3a4b',
         dir='case1_input', media=['photo.jpg', 'notes@home.txt', 'empty.bin']),
    dict(name='noVersionNoMedia', seed=200, formId='a&b"<\'>@', version=None,
         instanceId='uuid:x y', dir='case2_input', media=[]),
]


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


def b64(data):
    return dart_str(base64.b64encode(data).decode())


def main():
    tmp = tempfile.mkdtemp()
    subprocess.check_call(['javac', '-cp', CP, '-d', tmp, os.path.join(HERE, 'Golden.java')])
    pub = open(os.path.join(HERE, 'test_public_key.b64')).read().strip()
    text = subprocess.check_output(['openssl', 'rsa', '-in', os.path.join(HERE, 'test_private_key.pem'),
                                    '-noout', '-text'], text=True)

    def field(name):
        m = re.search(name + r':\s*\n((?:\s+[0-9a-f:]+\n)+)', text)
        return m.group(1).replace(':', '').replace(' ', '').replace('\n', '').lstrip('0') or '0'

    out = ['// GENERATED by tool/golden/generate.py. Do not edit.', '',
           "import 'golden_case.dart';", '',
           '/// The test RSA key (2048 bits): X.509 SubjectPublicKeyInfo, base64.',
           'const testPublicKeyBase64 = ' + dart_str(pub) + ';', '',
           '/// The test key\'s modulus (hex).',
           'const testModulusHex = ' + dart_str(field('modulus')) + ';', '',
           '/// The test key\'s private exponent (hex).',
           'const testPrivateExponentHex = ' + dart_str(field('privateExponent')) + ';', '',
           '/// Encryptions made by Collect\'s algorithm on the JVM.',
           'const goldenCases = [']
    for c in CASES:
        o = os.path.join(tmp, c['name'])
        d = os.path.join(HERE, c['dir'])
        args = ['java', '-cp', tmp + ':' + CP, 'Golden', o, pub, str(c['seed']), c['formId'],
                c['version'] or '-', c['instanceId'], os.path.join(d, 'submission.xml')]
        args += [os.path.join(d, m) for m in c['media']]
        subprocess.check_call(args)
        rd = lambda p: open(p, 'rb').read()
        names = c['media'] + ['submission.xml']
        out += ['  GoldenCase(',
                '    name: ' + dart_str(c['name']) + ',',
                '    seed: %d,' % c['seed'],
                '    formId: ' + dart_str(c['formId']) + ',',
                '    formVersion: ' + (dart_str(c['version']) if c['version'] else 'null') + ',',
                '    instanceId: ' + dart_str(c['instanceId']) + ',',
                '    submissionXml: ' + b64(rd(os.path.join(d, 'submission.xml'))) + ',',
                '    media: {']
        out += ['      %s: %s,' % (dart_str(m), b64(rd(os.path.join(d, m)))) for m in c['media']]
        out += ['    },',
                '    manifest: ' + dart_str(rd(os.path.join(o, 'manifest.xml')).decode('utf-8')) + ',',
                '    signatureSource: ' + dart_str(rd(os.path.join(o, 'signature-source.txt')).decode('utf-8')) + ',',
                '    encryptedFiles: {']
        out += ['      %s: %s,' % (dart_str(n + '.enc'), b64(rd(os.path.join(o, n + '.enc')))) for n in names]
        out += ['    },', '  ),']
    out += ['];', '']
    for f, var in [('encrypted.xml', 'collectEncryptedForm'),
                   ('encrypted-no-instanceID.xml', 'collectEncryptedNoInstanceIdForm'),
                   ('one-question-encrypted-unicode.xml', 'collectEncryptedUnicodeForm')]:
        out += ['/// Collect\'s test-forms/' + f + '.',
                'const ' + var + ' = r\'\'\'' + open(os.path.join(HERE, 'forms', f)).read() + '\'\'\';', '']
    path = os.path.join(PKG, 'test', 'src', 'golden_fixtures.dart')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write('\n'.join(out))
    subprocess.check_call(['dart', 'format', path])


main()
